GET http://localhost:5000/getTokenFromUser/eric/

####
GET http://localhost:5000/getUser/eric/

####

POST http://localhost:5000/hashtags/test/

####

GET http://localhost:5000/personalized/Chaitanya/timeline
####


POST http://localhost:5000/followRelationShip/Bhargav/user_activities/Chaitanya/user_activities
####

POST http://localhost:5000/addBatchFeed/
content-type: application/json

{
    "activity":{
    "actor": "SU:undefined",
    "attachments": {
        "files": [],
        "images": []
    },
    "duration": "7.04ms",
    "foreign_id": "",
    "id": "c1fb1f8d-340b-11ed-b6c3-06e4bae230b4",
    "object": "test user-c",
    "origin": null,
    "target": "",
    "text": "test user-c",
    "time": "2022-09-14T09:01:02.209832",
    "verb": "post"
}
}
####
get  http://localhost:5000/follow/timeline/Chaitanya/Chaitanya/
####
get http://localhost:5000/followings/Don/
####
get http://localhost:5000/followers/Don/
####
get http://localhost:5000/followStats/Bhargav/
####
POST http://localhost:5000/followRelationShip/Bhargav/user_activities/Chaitanya/user_activities/
####

POST http://localhost:5000/unFollow/Chaitanya/notification/Chaitanya/timeline

####

